/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2013-05-08 01:30:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class define_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=en>\r\n");
      out.write("\t<head>\r\n");
      out.write("    \t<meta charset=UTF-8>\r\n");
      out.write("\t\t<title>Collaboration Problem Diagnosis</title>\r\n");
      out.write("\t\t<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t\t<link href=\"css/buttons.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"js/jquery.placeholder.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"js/jquery.placeholder.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"js/jquery-1.6.2.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t\t$('input[placeholder]').placeholder();\r\n");
      out.write("\t</script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function getUrlVars()\r\n");
      out.write("    {\r\n");
      out.write("        var vars = [], hash;\r\n");
      out.write("        var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');\r\n");
      out.write("        for(var i = 0; i < hashes.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("            hash = hashes[i].split('=');\r\n");
      out.write("            vars.push(hash[0]);\r\n");
      out.write("            vars[hash[0]] = hash[1];\r\n");
      out.write("        }\r\n");
      out.write("        return vars;\r\n");
      out.write("    }\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("    \tvar allVars = getUrlVars();\r\n");
      out.write("    \tvar count = 0;\r\n");
      out.write("    \tfor (var key in allVars) {\r\n");
      out.write("    \t\tif (count == 2 || count == 3) {\r\n");
      out.write("    \t\t\tdocument.getElementById(\"file\"+(count-1)).name = key;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tcount++;\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" width=\"980\" height=\"150\" alt=\"logo\" style=\"vertical-align:middle;\"/> \r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<img src=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\" alt=\"logo_banner\" />\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"upload.jsp\">Upload your data files</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"define.jsp\">Define diagnostic parameters</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Diagnosis report</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About the project</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t    <div id=\"logout\">\r\n");
      out.write("\t\t\t\t\t<p>Signed in as </p> <br/>\r\n");
      out.write("\t\t\t\t\t<p><i><b>");
      out.print(request.getRemoteUser());
      out.write(" </b></i></p> <br/>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"logout.jsp\"> logout </a></p>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t<h2>Define diagnostic parameters </h2>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("    \r\n");
      out.write("\t\t\t\t\t<p>Here you need to specify the values of the parameters that Diag will use for diagnosing. </p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<hr /> <br/> \r\n");
      out.write("          <form action=\"MainController\" method=\"post\">         \r\n");
      out.write("                    <p> Course ID: <input type=\"text\" name=\"course\" id=\"courseID\" placeholder=\"please input your course id here\"/> (e.g. CS001) </p> <br />\r\n");
      out.write("\t\r\n");
      out.write("    \t\t <fieldset id=\"paraArea\">\r\n");
      out.write("\t\t\t\t<legend>List of diagnostic parameters:</legend> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t<label for=\"groupsize\">Problem 1 - percentage_groupsize_most:</label> \r\n");
      out.write("                  <input type=\"text\" name=\"p1\" id=\"groupsize\" size=\"10\" /> % <br/>\r\n");
      out.write("                    <i>i.e. the percentage of the size of a group defining relative majority</i>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t<label for=\"feedback\">Problem 1 - percentage_avegroupfeedback_large:</label> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"p2\" id=\"feedback\" size=\"30\" /> % <br/>\r\n");
      out.write("                    <i>i.e. the percentage of the average number of feedback by all groups for defining relatively large number of feedback produced by a group</i>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t<label for=\"grouppost\">Problem 2 - grouppost_few:</label> \r\n");
      out.write("                    <input type=\"text\" name=\"p3\" id=\"grouppost\" size=\"30\" /> <br />\r\n");
      out.write("                    <i>i.e. the number of posts that can be defined as relatively few for a group project</i>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t<label for=\"postmost\">Problem 2 - percentage_grouppost_most:</label> \r\n");
      out.write("                    <input type=\"text\" name=\"p4\" id=\"postmost\" size=\"30\" /> % <br />\r\n");
      out.write("                    <i>i.e. the percentage of the overall number of posts made by a group for defining relative majority</i>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t<label for=\"groupsize\">Problem 2 - percentage_groupsize_most:</label> \r\n");
      out.write("                    <input type=\"text\" name=\"p5\" id=\"groupsize\" size=\"30\" /> % <br />\r\n");
      out.write("                    <i>i.e. the percentage of the size of a group defining relative majority of a group</i>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"file1\" name=\"\" value=\"on\"/>\r\n");
      out.write("   \t\t\t\t<input type=\"hidden\" id=\"file2\" name=\"\" value=\"on\"/>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("\r\n");
      out.write("                <p> \r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class='super orange button' style=\"border: none; position:relative; top:365px;\">Diagnose</button> \r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t   </form>\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t\t\t<img src=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\" alt=\"logo_banner\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\tDiag&trade; © 2011 | Design by Shuangyan Liu | All rights reserved.\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
