/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2013-05-08 01:25:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=en>\r\n");
      out.write("\t<head>\r\n");
      out.write("    \t<meta charset=UTF-8>\r\n");
      out.write("\t\t<title>Collaboration Problem Diagnosis</title>\r\n");
      out.write("\t\t<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t\t<link href=\"css/buttons.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" width=\"980\" height=\"150\" alt=\"logo\" style=\"vertical-align:middle;\"/> \r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<img src=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\" alt=\"logo_banner\" />\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"upload.jsp\">Upload your data files</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Define diagnostic parameters</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Diagnosis report</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About the project</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("               <div id=\"logout\">\r\n");
      out.write("\t\t\t\t<p>Signed in as </p> <br/>\r\n");
      out.write("\t\t\t\t<p><i><b>");
      out.print(request.getRemoteUser());
      out.write(" </b></i></p> <br/>\r\n");
      out.write("\t\t\t\t<p><a href=\"logout.jsp\"> logout </a></p>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("               </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t<h2>Welcome to Diag&trade; </h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<p>Diag is a web application capable of supporting teachers or facilitators to assess group collaboration problems that are possessed by the online collaborative learning groups examined. It incorporates the latest research in online collaborative learning - a diagnostic mechanism for ascertaining the existence of major collaboration problems. </p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<p>With Diag, teachers or facilitators can understand and evaluate how individual groups and students perform in completing a piece of collaborative group work.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"left\">\r\n");
      out.write("\t\t\t\t\t<h2>Overview</h2>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br /> <br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<img src=\"images/overview.jpg\" title=\"overview\" alt=\"overview\" /><br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"right\">\r\n");
      out.write("\t\t\t\t\t<h2>Start Diagnosing</h2>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                    <br /> \r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<p>To achieve a diagnostic goal, you need to complete the first two stages of the overall procedure - upload your data files and define the parameters for diagnosing.</p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href='upload.jsp' class='super orange button'>Start Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- clear:both is used to extend the margin of this box and clear the float that may fly over it.-->\r\n");
      out.write("\t\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t\t\t<img src=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\" alt=\"logo_banner\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\tDiag&trade; © 2011 | Design by Shuangyan Liu | All rights reserved.\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
