/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2013-05-08 01:29:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=en>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=UTF-8>\r\n");
      out.write("\t\t<title>Collaboration Problem Diagnosis</title>\r\n");
      out.write("\t\t<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t\t<link href=\"css/buttons.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\"\r\n");
      out.write("\tsrc=\"js/jquery-1.6.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"/js/JSON2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- automatically check if data files are already uploaded.\r\n");
      out.write("If yes, list the data files-->\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t$.get('FileQuery', function(data, textStatus) {\r\n");
      out.write("\t\t// this gives an array of objects\r\n");
      out.write("\t\tvar files = JSON.parse(data);\r\n");
      out.write("\t\t$(\"#filecheck\").empty();\r\n");
      out.write("\t\t// iterate over files and produce a list of checkboxes\r\n");
      out.write("\t\tfor ( var x = 0; x < files.length; x++) {\r\n");
      out.write("\t\t\tvar fileName = files[x];\r\n");
      out.write("\t\t\tvar file = '<input type=\"checkbox\" name=\"' + fileName + '\"/>'\r\n");
      out.write("\t\t\t\t\t+ fileName + '<br>';\r\n");
      out.write("\t\t\t$(\"#filecheck\").prepend(file);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, 'text');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction getFiles() {\r\n");
      out.write("\t\t$.get('FileQuery', function(data, textStatus) {\r\n");
      out.write("\t\t\tvar files = JSON.parse(data);\r\n");
      out.write("\t\t\t$(\"#filecheck\").empty();\r\n");
      out.write("\t\t\tfor ( var x = 0; x < files.length; x++) {\r\n");
      out.write("\t\t\t\tvar fileName = files[x];\r\n");
      out.write("\t\t\t\tvar file = '<input type=\"checkbox\" name=\"' + fileName\r\n");
      out.write("\t\t\t\t\t\t+ '\"/>' + fileName + '<br>';\r\n");
      out.write("\t\t\t\t$(\"#filecheck\").prepend(file);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, 'text');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar req;\r\n");
      out.write("\r\n");
      out.write("\tfunction ajaxFunction() {\r\n");
      out.write("\t\tvar url = \"HandleFileUpload\";\r\n");
      out.write("\r\n");
      out.write("\t\treq = new XMLHttpRequest();\r\n");
      out.write("\t\treq.onreadystatechange = checkFileUploadStatus;\r\n");
      out.write("\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\treq.open(\"GET\", url, true);\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\talert(e);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treq.send(null);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkFileUploadStatus() {\r\n");
      out.write("\t\tif (req.readyState == 4) {\r\n");
      out.write("\t\t\tif (req.status == 200) {\r\n");
      out.write("\t\t\t\tvar xml = req.responseText;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (xml == \"tryagain\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\twindow.setTimeout(\"ajaxFunction();\", 100);\r\n");
      out.write("\t\t\t\t} else if (xml == \"uploaddone\") {\r\n");
      out.write("\t\t\t\t\tgetFiles();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<img src=\"images/logo.png\" width=\"980\" height=\"150\" alt=\"logo\"\r\n");
      out.write("\t\t\t\tstyle=\"vertical-align: middle;\" /> <br /> <img\r\n");
      out.write("\t\t\t\tsrc=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\"\r\n");
      out.write("\t\t\t\talt=\"logo_banner\" />\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"upload.jsp\">Upload your data files</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"define.jsp\">Define diagnostic parameters</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Diagnosis report</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">About the project</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("               <div id=\"logout\">\r\n");
      out.write("\t\t\t\t<p>Signed in as </p> <br/>\r\n");
      out.write("\t\t\t\t<p><i><b>");
      out.print(request.getRemoteUser());
      out.write(" </b></i></p> <br/>\r\n");
      out.write("\t\t\t\t<p><a href=\"logout.jsp\"> logout </a></p>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("               </div>\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t<h2>Upload your data files</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>Here you need to upload the data that you have collected and\r\n");
      out.write("\t\t\t\t\trepresent student interactions with a collaborative learning\r\n");
      out.write("\t\t\t\t\tsystem.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>Two data files (.csv files) are expected. The first file is\r\n");
      out.write("\t\t\t\t\tto contain data accounting for the behaviours of collaborative\r\n");
      out.write("\t\t\t\t\tgroups, namely group data. The second is to include data revealing\r\n");
      out.write("\t\t\t\t\tthe behaviours of individual students, namely student data. A data\r\n");
      out.write("\t\t\t\t\tfile should start with the prefix \"group_\" (for group data) or\r\n");
      out.write("\t\t\t\t\t\"student_\"(for student data).</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>You could refer to the example data files (<a href=\"res/group_1.csv\">group_1.csv</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"res/student_1.csv\">student_1.csv</a>) for further details when you prepare your own data\r\n");
      out.write("\t\t\t\t\tfiles.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"left\">\r\n");
      out.write("\t\t\t\t<h2>List of data files uploaded</h2>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<p>Please select your data files from the list below.</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form id=\"filecheck\" name=\"selectedFileForm\" action=\"define.jsp\" method=\"get\"></form>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p>If no files uploaded before, use the following upload button\r\n");
      out.write("\t\t\t\t\tfor uploading:</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- file upload -->\r\n");
      out.write("\t\t\t\t<div id=\"uploadform\">\r\n");
      out.write("\t\t\t\t\t<form id=\"myForm\" enctype=\"multipart/form-data\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"uploadFrame\" action=\"HandleFileUpload\"\r\n");
      out.write("\t\t\t\t\t\tonsubmit=\"ajaxFunction()\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" name=\"txtFile\" id=\"txtFile\" /><br /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" style=\"border: none;\" class='large green button'  name=\"submit\" value=\"Upload\"  />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<iframe id=\"uploadFrameID\" name=\"uploadFrame\" height=\"0\" width=\"0\"\r\n");
      out.write("\t\t\t\t\tframeborder=\"0\" scrolling=\"yes\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br /> <br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>Proceed with the diagnosis procedure, press the 'next'\r\n");
      out.write("\t\t\t\t\tbutton.</p>\r\n");
      out.write("\t\t\t\t<a href='#' class='super orange button' onclick='document.forms[\"selectedFileForm\"].submit();'>Next</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- clear:both is used to extend the margin of this box and clear the float that may fly over it.-->\r\n");
      out.write("\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t\t<img src=\"images/bg_banner_grey.gif\" width=\"980\" height=\"5\"\r\n");
      out.write("\t\t\talt=\"logo_banner\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<footer> Diag&trade; © 2011 | Design by Shuangyan Liu | All\r\n");
      out.write("\t\t\trights reserved. </footer>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
